### ISSUE TITLE
Create a data insert function to DB

### ISSUE THREAD

**Issue by abdullah2205** [abdullah2205/laravel-simple-crud#1]

**Comment by naufalboy** [comment]
can i contribute by trying to solve the issue?

**Comment by abdullah2205** [comment]
Of course, but submit only valid PR :)

**Comment by abdullah2205** [comment]
Good luck !

**Comment by luckys383** [comment]
@abdullah2205 can you explain little bit more what you want to achieve with this? So I can help you to solve this issue.

**Comment by abdullah2205** [comment]
Fix
